---

- import_role:
    name: get-inventory-hosts
  vars:
    inventory_pattern: "{{ rvar_ids_coordinators_inventory_pattern }}"
    inventory_action: second_level_lookup
    inventory_hosts_property: ansible_default_ipv4
    inventory_hosts_property_2ndlevel: address
    inventory_hosts_clear_first: true
    inventory_hosts_add_prefix: ""
    inventory_hosts_add_suffix: ":{{ ids_transport_tcp_port }}"
  when: ids_discovery_seed_by_fqdns|default()|bool == false

- import_role:
    name: get-inventory-hosts
  vars:
    inventory_pattern: "{{ rvar_ids_coordinators_inventory_pattern }}"
    inventory_action: first_level_lookup
    inventory_hosts_property: "ansible_fqdn"
    inventory_hosts_property_2ndlevel: ""
    inventory_hosts_clear_first: true
    inventory_hosts_add_prefix: ""
    inventory_hosts_add_suffix: ":{{ ids_transport_tcp_port }}"
  when: ids_discovery_seed_by_fqdns|default()|bool

- name: Set ids_discovery_seed_hosts facts
  set_fact:
    rout_ids_discovery_seed_hosts: "{{ output_inventory_hosts }}"