---

  - name: "Update config file {{ ids_install_ids_jvm_options_file }} with rvar_jvm_params params if defined"
    lineinfile:
      path: "{{ ids_install_ids_jvm_options_file }}"
      regexp: '^{{ item }}'
      insertafter: '^#{{ item }}'
      line: "{{ item }}"
    with_items: "{{ rvar_jvm_params }}"
    when: rvar_jvm_params is defined and (rvar_jvm_params|length > 0)