---

  - name: "Update config file {{ ids_install_ids_jvm_options_file }} with rvar_jvm_mem_min param if defined"
    lineinfile:
      path: "{{ ids_install_ids_jvm_options_file }}"
      regexp: '^{{ item.key }}'
      insertafter: '^#{{ item.key }}'
      line: "{{ item.key }}{{ item.value }}"
    with_dict:
      "-Xms": "{{ rvar_jvm_mem_min }}m"
    when: rvar_jvm_mem_min is defined and rvar_jvm_mem_min != ""

  - name: "Update config file {{ ids_install_ids_jvm_options_file }} with rvar_jvm_mem_max param if defined"
    lineinfile:
      path: "{{ ids_install_ids_jvm_options_file }}"
      regexp: '^{{ item.key }}'
      insertafter: '^#{{ item.key }}'
      line: "{{ item.key }}{{ item.value }}"
    with_dict:
      "-Xmx": "{{ rvar_jvm_mem_max }}m"
    when: rvar_jvm_mem_max is defined and rvar_jvm_mem_max != ""